// <auto-generated />
using BastinWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BastinWebApp.Migrations
{
    [DbContext(typeof(BastinWebAppContext))]
    partial class BastinWebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BastinWebApp.Models.Gebruiker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Gebruikersnaam");

                    b.Property<string>("Paswoord");

                    b.Property<string>("Privileges");

                    b.HasKey("ID");

                    b.ToTable("Gebruiker");
                });

            modelBuilder.Entity("BastinWebApp.Models.Melding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AfbeeldingPad");

                    b.Property<int>("Afdeling");

                    b.Property<DateTime>("AgendaDatum");

                    b.Property<DateTime>("Datum");

                    b.Property<int?>("GebruikerID");

                    b.Property<string>("Klant");

                    b.Property<string>("Link");

                    b.Property<int>("Machine");

                    b.Property<string>("Omschrijving");

                    b.Property<string>("Ondertitel");

                    b.Property<string>("ProcedurePad");

                    b.Property<string>("Titel");

                    b.Property<int>("TypeMelding");

                    b.HasKey("ID");

                    b.HasIndex("GebruikerID");

                    b.ToTable("Melding");
                });

            modelBuilder.Entity("BastinWebApp.Models.Privilege", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Privileges");

                    b.HasKey("ID");

                    b.ToTable("Privilege");
                });

            modelBuilder.Entity("BastinWebApp.Models.Melding", b =>
                {
                    b.HasOne("BastinWebApp.Models.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("GebruikerID");
                });
#pragma warning restore 612, 618
        }
    }
}
